---
AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:

  Mapper:
    Type: AWS::Serverless::Function
    Properties:
      Handler: mapper
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /map
            Method: get

Outputs:

  Endpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"